/** Duration in ms for which the icon stating the text has been copied to the clipboard is displayed */
export const COPIED_TO_CLIPBOARD_ICON_TIMEOUT = 2000;
export const COUNTRY_CODES = [
  {
    country: "Albania",
    alpha2: "AL",
    latitude: 41,
    longitude: 20,
    continent: "Europe",
  },
  {
    country: "Algeria",
    alpha2: "DZ",
    latitude: 28,
    longitude: 3,
    continent: "Africa",
  },
  {
    country: "American Samoa",
    alpha2: "AS",
    latitude: -14.3333,
    longitude: -170,
    continent: "Oceania",
  },
  {
    country: "Andorra",
    alpha2: "AD",
    latitude: 42.5,
    longitude: 1.6,
    continent: "Europe",
  },
  {
    country: "Angola",
    alpha2: "AO",
    latitude: -12.5,
    longitude: 18.5,
    continent: "Africa",
  },
  {
    country: "Anguilla",
    alpha2: "AI",
    latitude: 18.25,
    longitude: -63.1667,
    continent: "North America",
  },
  {
    country: "Antarctica",
    alpha2: "AQ",
    latitude: -90,
    longitude: 0,
    continent: "Antarctica",
  },
  {
    country: "Antigua and Barbuda",
    alpha2: "AG",
    latitude: 17.05,
    longitude: -61.8,
    continent: "North America",
  },
  {
    country: "Argentina",
    alpha2: "AR",
    latitude: -34,
    longitude: -64,
    continent: "South America",
  },
  {
    country: "Armenia",
    alpha2: "AM",
    latitude: 40,
    longitude: 45,
    continent: "Asia",
  },
  {
    country: "Aruba",
    alpha2: "AW",
    latitude: 12.5,
    longitude: -69.9667,
    continent: "North America",
  },
  {
    country: "Australia",
    alpha2: "AU",
    latitude: -27,
    longitude: 133,
    continent: "Oceania",
  },
  {
    country: "Austria",
    alpha2: "AT",
    latitude: 47.3333,
    longitude: 13.3333,
    continent: "Europe",
  },
  {
    country: "Azerbaijan",
    alpha2: "AZ",
    latitude: 40.5,
    longitude: 47.5,
    continent: "Asia",
  },
  {
    country: "Bahamas",
    alpha2: "BS",
    latitude: 24.25,
    longitude: -76,
    continent: "North America",
  },
  {
    country: "Bahrain",
    alpha2: "BH",
    latitude: 26,
    longitude: 50.55,
    continent: "Asia",
  },
  {
    country: "Bangladesh",
    alpha2: "BD",
    latitude: 24,
    longitude: 90,
    continent: "Asia",
  },
  {
    country: "Barbados",
    alpha2: "BB",
    latitude: 13.1667,
    longitude: -59.5333,
    continent: "North America",
  },
  {
    country: "Belarus",
    alpha2: "BY",
    latitude: 53,
    longitude: 28,
    continent: "Europe",
  },
  {
    country: "Belgium",
    alpha2: "BE",
    latitude: 50.8333,
    longitude: 4,
    continent: "Europe",
  },
  {
    country: "Belize",
    alpha2: "BZ",
    latitude: 17.25,
    longitude: -88.75,
    continent: "North America",
  },
  {
    country: "Benin",
    alpha2: "BJ",
    latitude: 9.5,
    longitude: 2.25,
    continent: "Africa",
  },
  {
    country: "Bermuda",
    alpha2: "BM",
    latitude: 32.3333,
    longitude: -64.75,
    continent: "North America",
  },
  {
    country: "Bhutan",
    alpha2: "BT",
    latitude: 27.5,
    longitude: 90.5,
    continent: "Asia",
  },
  {
    country: "Bolivia, Plurinational State of",
    alpha2: "BO",
    latitude: -17,
    longitude: -65,
    continent: "South America",
  },
  {
    country: "Bosnia and Herzegovina",
    alpha2: "BA",
    latitude: 44,
    longitude: 18,
    continent: "Europe",
  },
  {
    country: "Botswana",
    alpha2: "BW",
    latitude: -22,
    longitude: 24,
    continent: "Africa",
  },
  {
    country: "Bouvet Island",
    alpha2: "BV",
    latitude: -54.4333,
    longitude: 3.4,
    continent: "Antarctica",
  },
  {
    country: "Brazil",
    alpha2: "BR",
    latitude: -10,
    longitude: -55,
    continent: "South America",
  },
  {
    country: "British Indian Ocean Territory",
    alpha2: "IO",
    latitude: -6,
    longitude: 71.5,
    continent: "Asia",
  },
  {
    country: "Brunei Darussalam",
    alpha2: "BN",
    latitude: 4.5,
    longitude: 114.6667,
    continent: "Asia",
  },
  {
    country: "Bulgaria",
    alpha2: "BG",
    latitude: 43,
    longitude: 25,
    continent: "Europe",
  },
  {
    country: "Burkina Faso",
    alpha2: "BF",
    latitude: 13,
    longitude: -2,
    continent: "Africa",
  },
  {
    country: "Burundi",
    alpha2: "BI",
    latitude: -3.5,
    longitude: 30,
    continent: "Africa",
  },
  {
    country: "Cambodia",
    alpha2: "KH",
    latitude: 13,
    longitude: 105,
    continent: "Asia",
  },
  {
    country: "Cameroon",
    alpha2: "CM",
    latitude: 6,
    longitude: 12,
    continent: "Africa",
  },
  {
    country: "Canada",
    alpha2: "CA",
    latitude: 60,
    longitude: -95,
    continent: "North America",
  },
  {
    country: "Cape Verde",
    alpha2: "CV",
    latitude: 16,
    longitude: -24,
    continent: "Africa",
  },
  {
    country: "Cayman Islands",
    alpha2: "KY",
    latitude: 19.5,
    longitude: -80.5,
    continent: "North America",
  },
  {
    country: "Central African Republic",
    alpha2: "CF",
    latitude: 7,
    longitude: 21,
    continent: "Africa",
  },
  {
    country: "Chad",
    alpha2: "TD",
    latitude: 15,
    longitude: 19,
    continent: "Africa",
  },
  {
    country: "Chile",
    alpha2: "CL",
    latitude: -30,
    longitude: -71,
    continent: "South America",
  },
  {
    country: "China",
    alpha2: "CN",
    latitude: 35,
    longitude: 105,
    continent: "Asia",
  },
  {
    country: "Christmas Island",
    alpha2: "CX",
    latitude: -10.5,
    longitude: 105.6667,
    continent: "Asia",
  },
  {
    country: "Cocos (Keeling) Islands",
    alpha2: "CC",
    latitude: -12.5,
    longitude: 96.8333,
    continent: "Asia",
  },
  {
    country: "Colombia",
    2: "CO",
    latitude: 4,
    longitude: -72,
    continent: "South America",
  },
  {
    country: "Comoros",
    alpha: "KM",
    latitude: -12.1667,
    longitude: 44.25,
    continent: "Africa",
  },
  {
    country: "Congo",
    alpha2: "CG",
    latitude: -1,
    longitude: 15,
    continent: "Africa",
  },
  {
    country: "Congo, the Democratic Republic of the",
    alpha2: "CD",
    latitude: 0,
    longitude: 25,
    continent: "Africa",
  },
  {
    country: "Cook Islands",
    alpha2: "CK",
    latitude: -21.2333,
    longitude: -159.7667,
    continent: "Oceania",
  },
  {
    country: "Costa Rica",
    alpha2: "CR",
    latitude: 10,
    longitude: -84,
    continent: "North America",
  },
  {
    country: "Côte d'Ivoire",
    alpha2: "CI",
    latitude: 8,
    longitude: -5,
    continent: "Africa",
  },
  {
    country: "Croatia",
    alpha2: "HR",
    latitude: 45.1667,
    longitude: 15.5,
    continent: "Europe",
  },
  {
    country: "Cuba",
    alpha2: "CU",
    latitude: 21.5,
    longitude: -80,
    continent: "North America",
  },
  {
    country: "Cyprus",
    alpha2: "CY",
    latitude: 35,
    longitude: 33,
    continent: "Asia",
  },
  {
    country: "Czech Republic",
    alpha2: "CZ",
    latitude: 49.75,
    longitude: 15.5,
    continent: "Europe",
  },
  {
    country: "Denmark",
    alpha2: "DK",
    latitude: 56,
    longitude: 10,
    continent: "Europe",
  },
  {
    country: "Djibouti",
    alpha2: "DJ",
    latitude: 11.5,
    longitude: 43,
    continent: "Africa",
  },
  {
    country: "Dominica",
    alpha2: "DM",
    latitude: 15.4167,
    longitude: -61.3333,
    continent: "North America",
  },
  {
    country: "Dominican Republic",
    alpha2: "DO",
    latitude: 19,
    longitude: -70.6667,
    continent: "North America",
  },
  {
    country: "Ecuador",
    alpha2: "EC",
    latitude: -2,
    longitude: -77.5,
    continent: "South America",
  },
  {
    country: "Egypt",
    alpha2: "EG",
    latitude: 27,
    longitude: 30,
    continent: "Africa",
  },
  {
    country: "El Salvador",
    alpha2: "SV",
    latitude: 13.8333,
    longitude: -88.9167,
    continent: "North America",
  },
  {
    country: "Equatorial Guinea",
    alpha2: "GQ",
    latitude: 2,
    longitude: 10,
    continent: "Africa",
  },
  {
    country: "Eritrea",
    alpha2: "ER",
    latitude: 15,
    longitude: 39,
    continent: "Africa",
  },
  {
    country: "Estonia",
    alpha2: "EE",
    latitude: 59,
    longitude: 26,
    continent: "Europe",
  },
  {
    country: "Ethiopia",
    alpha2: "ET",
    latitude: 8,
    longitude: 38,
    continent: "Africa",
  },
  {
    country: "Falkland Islands (Malvinas)",
    alpha2: "FK",
    latitude: -51.75,
    longitude: -59,
    continent: "South America",
  },
  {
    country: "Faroe Islands",
    alpha2: "FO",
    latitude: 62,
    longitude: -7,
    continent: "Europe",
  },
  {
    country: "Fiji",
    alpha2: "FJ",
    latitude: -18,
    longitude: 175,
    continent: "Oceania",
  },
  {
    country: "Finland",
    alpha2: "FI",
    latitude: 64,
    longitude: 26,
    continent: "Europe",
  },
  {
    country: "France",
    alpha2: "FR",
    latitude: 46,
    longitude: 2,
    continent: "Europe",
  },
  {
    country: "French Guiana",
    alpha2: "GF",
    latitude: 4,
    longitude: -53,
    continent: "South America",
  },
  {
    country: "French Polynesia",
    alpha2: "PF",
    latitude: -15,
    longitude: -140,
    continent: "Oceania",
  },
  {
    country: "French Southern Territories",
    alpha2: "TF",
    latitude: -43,
    longitude: 67,
    continent: "Antarctica",
  },
  {
    country: "Gabon",
    alpha2: "GA",
    latitude: -1,
    longitude: 11.75,
    continent: "Africa",
  },
  {
    country: "Gambia",
    alpha2: "GM",
    latitude: 13.4667,
    longitude: -16.5667,
    continent: "Africa",
  },
  {
    country: "Georgia",
    alpha2: "GE",
    latitude: 42,
    longitude: 43.5,
    continent: "Asia",
  },
  {
    country: "Germany",
    alpha2: "DE",
    latitude: 51,
    longitude: 9,
    continent: "Europe",
  },
  {
    country: "Ghana",
    alpha2: "GH",
    latitude: 8,
    longitude: -2,
    continent: "Africa",
  },
  {
    country: "Gibraltar",
    alpha2: "GI",
    latitude: 36.1833,
    longitude: -5.3667,
    continent: "Europe",
  },
  {
    country: "Greece",
    alpha2: "GR",
    latitude: 39,
    longitude: 22,
    continent: "Europe",
  },
  {
    country: "Greenland",
    alpha2: "GL",
    latitude: 72,
    longitude: -40,
    continent: "North America",
  },
  {
    country: "Grenada",
    alpha2: "GD",
    latitude: 12.1167,
    longitude: -61.6667,
    continent: "North America",
  },
  {
    country: "Guadeloupe",
    alpha2: "GP",
    latitude: 16.25,
    longitude: -61.5833,
    continent: "North America",
  },
  {
    country: "Guam",
    alpha2: "GU",
    latitude: 13.4667,
    longitude: 144.7833,
    continent: "Oceania",
  },
  {
    country: "Guatemala",
    alpha2: "GT",
    latitude: 15.5,
    longitude: -90.25,
    continent: "North America",
  },
  {
    country: "Guernsey",
    alpha2: "GG",
    latitude: 49.5,
    longitude: -2.56,
    continent: "Europe",
  },
  {
    country: "Guinea",
    alpha2: "GN",
    latitude: 11,
    longitude: -10,
    continent: "Africa",
  },
  {
    country: "Guinea-Bissau",
    alpha2: "GW",
    latitude: 12,
    longitude: -15,
    continent: "Africa",
  },
  {
    country: "Guyana",
    alpha2: "GY",
    latitude: 5,
    longitude: -59,
    continent: "South America",
  },
  {
    country: "Haiti",
    alpha2: "HT",
    latitude: 19,
    longitude: -72.4167,
    continent: "North America",
  },
  {
    country: "Heard Island and McDonald Islands",
    alpha2: "HM",
    latitude: -53.1,
    longitude: 72.5167,
    continent: "Antarctica",
  },
  {
    country: "Holy See (Vatican City State)",
    alpha2: "VA",
    latitude: 41.9,
    longitude: 12.45,
    continent: "Europe",
  },
  {
    country: "Honduras",
    alpha2: "HN",
    latitude: 15,
    longitude: -86.5,
    continent: "North America",
  },
  {
    country: "Hong Kong",
    alpha2: "HK",
    latitude: 22.25,
    longitude: 114.1667,
    continent: "Asia",
  },
  {
    country: "Hungary",
    alpha2: "HU",
    latitude: 47,
    longitude: 20,
    continent: "Europe",
  },
  {
    country: "Iceland",
    alpha2: "IS",
    latitude: 65,
    longitude: -18,
    continent: "Europe",
  },
  {
    country: "India",
    alpha2: "IN",
    latitude: 20,
    longitude: 77,
    continent: "Asia",
  },
  {
    country: "Indonesia",
    alpha2: "ID",
    latitude: -5,
    longitude: 120,
    continent: "Asia",
  },
  {
    country: "Iran, Islamic Republic of",
    alpha2: "IR",
    latitude: 32,
    longitude: 53,
    continent: "Asia",
  },
  {
    country: "Iraq",
    alpha2: "IQ",
    latitude: 33,
    longitude: 44,
    continent: "Asia",
  },
  {
    country: "Ireland",
    alpha2: "IE",
    latitude: 53,
    longitude: -8,
    continent: "Europe",
  },
  {
    country: "Isle of Man",
    alpha2: "IM",
    latitude: 54.23,
    longitude: -4.55,
    continent: "Europe",
  },
  {
    country: "Israel",
    alpha2: "IL",
    latitude: 31.5,
    longitude: 34.75,
    continent: "",
  },
  {
    country: "Italy",
    alpha2: "IT",
    latitude: 428333,
    longitude: 12.8333,
    continent: "Europe",
  },
  {
    country: "Jamaica",
    alpha2: "JM",
    latitude: 18.25,
    longitude: -77.5,
    continent: "North America",
  },
  {
    country: "Japan",
    alpha2: "JP",
    latitude: 36,
    longitude: 138,
    continent: "Asia",
  },
  {
    country: "Jersey",
    alpha2: "JE",
    latitude: 49.21,
    longitude: -2.13,
    continent: "Europe",
  },
  {
    country: "Jordan",
    alpha2: "JO",
    latitude: 31,
    longitude: 36,
    continent: "Asia",
  },
  {
    country: "Kazakhstan",
    alpha2: "KZ",
    latitude: 48,
    longitude: 68,
    continent: "Asia",
  },
  {
    country: "Kenya",
    alpha2: "KE",
    latitude: 1,
    longitude: 38,
    continent: "Africa",
  },
  {
    country: "Kiribati",
    alpha2: "KI",
    latitude: 1.4167,
    longitude: 173,
    continent: "Oceania",
  },
  {
    country: "Korea, Democratic People's Republic of",
    alpha2: "KP",
    latitude: 40,
    longitude: 127,
    continent: "Asia",
  },
  {
    country: "Korea, Republic of",
    alpha2: "KR",
    latitude: 37,
    longitude: 127.5,
    continent: "Asia",
  },
  {
    country: "Kuwait",
    alpha2: "KW",
    latitude: 29.3375,
    longitude: 47.6581,
    continent: "Asia",
  },
  {
    country: "Kyrgyzstan",
    alpha2: "KG",
    latitude: 41,
    longitude: 75,
    continent: "Asia",
  },
  {
    country: "Lao People's Democratic Republic",
    alpha2: "LA",
    latitude: 18,
    longitude: 105,
    continent: "Asia",
  },
  {
    country: "Latvia",
    alpha2: "LV",
    latitude: 57,
    longitude: 25,
    continent: "Europe",
  },
  {
    country: "Lebanon",
    alpha2: "LB",
    latitude: 33.8333,
    longitude: 0.8333,
    continent: "Asia",
  },
  {
    country: "Lesotho",
    alpha2: "LS",
    latitude: -29.5,
    longitude: 28.5,
    continent: "Africa",
  },
  {
    country: "Liberia",
    alpha2: "LR",
    latitude: 6.5,
    longitude: -9.5,
    continent: "Africa",
  },
  {
    country: "Libyan Arab Jamahiriya",
    alpha: "LY",
    latitude: 25,
    longitude: 17,
    continent: "Africa",
  },
  {
    country: "Liechtenstein",
    alpha2: "LI",
    latitude: 47.1667,
    longitude: 9.5333,
    continent: "Europe",
  },
  {
    country: "Lithuania",
    alpha2: "LT",
    latitude: 56,
    longitude: 24,
    continent: "Europe",
  },
  {
    country: "Luxembourg",
    alpha2: "LU",
    latitude: 49.75,
    longitude: 6.1667,
    continent: "Europe",
  },
  {
    country: "Macao",
    alpha2: "MO",
    latitude: 22.1667,
    longitude: 113.55,
    continent: "Asia",
  },
  {
    country: "Macedonia the former Yugoslav Republic of",
    alpha2: "MK",
    latitude: 41.8333,
    longitude: 22,
    continent: "Europe",
  },
  {
    country: "Madagascar",
    alpha2: "MG",
    latitude: -20,
    longitude: 47,
    continent: "Africa",
  },
  {
    country: "Malawi",
    alpha2: "MW",
    latitude: -13.5,
    longitude: 34,
    continent: "Africa",
  },
  {
    country: "Malaysia",
    alpha2: "MY",
    latitude: 2.5,
    longitude: 112.5,
    continent: "Asia",
  },
  {
    country: "Maldives",
    alpha2: "MV",
    latitude: 3.25,
    longitude: 73,
    continent: "Asia",
  },
  {
    country: "Mali",
    alpha2: "ML",
    latitude: 17,
    longitude: -4,
    continent: "Africa",
  },
  {
    country: "Malta",
    alpha2: "MT",
    latitude: 35.8333,
    longitude: 14.5833,
    continent: "Europe",
  },
  {
    country: "Marshall Islands",
    alpha2: "MH",
    latitude: 9,
    longitude: 168,
    continent: "Oceania",
  },
  {
    country: "Martinique",
    alpha2: "MQ",
    latitude: 14.6667,
    longitude: -61,
    continent: "North America",
  },
  {
    country: "Mauritania",
    alpha2: "MR",
    latitude: 20,
    longitude: -12,
    continent: "Africa",
  },
  {
    country: "Mauritius",
    alpha2: "MU",
    latitude: -20.2833,
    longitude: 57.55,
    continent: "Africa",
  },
  {
    country: "Mayotte",
    alpha2: "YT",
    latitude: -12.8333,
    longitude: 45.1667,
    continent: "Africa",
  },
  {
    country: "Mexico",
    alpha2: "MX",
    latitude: 23,
    longitude: -102,
    continent: "North America",
  },
  {
    country: "Micronesia, Federated States of",
    alpha2: "FM",
    latitude: 6.9167,
    longitude: 158.25,
    continent: "Oceania",
  },
  {
    country: "Moldova, Republic of",
    alpha2: "MD",
    latitude: 47,
    longitude: 29,
    continent: "Europe",
  },
  {
    country: "Monaco",
    alpha2: "",
    latitude: 43.7333,
    longitude: 7.4,
    continent: "",
  },
  {
    country: "Mongolia",
    alpha2: "MN",
    latitude: 46,
    longitude: 105,
    continent: "Asia",
  },
  {
    country: "Montenegro",
    alpha2: "ME",
    latitude: 42,
    longitude: 19,
    continent: "Europe",
  },
  {
    country: "Montserrat",
    alpha2: "MS",
    latitude: 16.75,
    longitude: -62.2,
    continent: "North America",
  },
  {
    country: "Morocco",
    alpha2: "MA",
    latitude: 32,
    longitude: -5,
    continent: "Africa",
  },
  {
    country: "Mozambique",
    alpha2: "MZ",
    latitude: -18.25,
    longitude: 35,
    continent: "Africa",
  },
  {
    country: "Myanmar",
    alpha2: "MM",
    latitude: 22,
    longitude: 98,
    continent: "Asia",
  },
  {
    country: "Namibia",
    alpha2: "NA",
    latitude: -22,
    longitude: 17,
    continent: "Africa",
  },
  {
    country: "Nauru",
    alpha2: "NR",
    latitude: -0.5333,
    longitude: 166.9167,
    continent: "Oceania",
  },
  {
    country: "Nepal",
    alpha2: "NP",
    latitude: 28,
    longitude: 84,
    continent: "Asia",
  },
  {
    country: "Netherlands",
    alpha2: "NL",
    latitude: 52.5,
    longitude: 5.75,
    continent: "Europe",
  },
  {
    country: "Netherlands Antilles",
    alpha2: "AN",
    latitude: 12.25,
    longitude: -68.75,
    continent: "North America",
  },
  {
    country: "Newedonia",
    alpha2: "NC",
    latitude: 21.5,
    longitude: 165.5,
    continent: "Oceania",
  },
  {
    country: "New Zealand",
    alpha2: "NZ",
    latitude: -41,
    longitude: 174,
    continent: "Oceania",
  },
  {
    country: "Nicaragua",
    alpha2: "NI",
    latitude: 13,
    longitude: -85,
    continent: "North America",
  },
  {
    country: "Niger",
    alpha2: "NE",
    latitude: 16,
    longitude: 8,
    continent: "Africa",
  },
  {
    country: "Nigeria",
    alpha2: "NG",
    latitude: 10,
    longitude: 8,
    continent: "Africa",
  },
  {
    country: "Niue",
    alpha2: "NU",
    latitude: -19.0333,
    longitude: -169.8667,
    continent: "Oceania",
  },
  {
    country: "Norfolk Island",
    alpha: "NF",
    latitude: -29.0333,
    longitude: 167.95,
    continent: "Oceania",
  },
  {
    country: "Northern Mariana Islands",
    alpha2: "MP",
    latitude: 15.2,
    longitude: 145.75,
    continent: "Oceania",
  },
  {
    country: "Norway",
    alpha2: "NO",
    latitude: 62,
    longitude: 10,
    continent: "Europe",
  },
  {
    country: "Oman",
    alpha2: "OM",
    latitude: 21,
    longitude: 57,
    continent: "Asia",
  },
  {
    country: "Pakistan",
    alpha2: "PK",
    latitude: 30,
    longitude: 70,
    continent: "Asia",
  },
  {
    country: "Palau",
    alpha2: "PW",
    latitude: 7.5,
    longitude: 134.5,
    continent: "Oceania",
  },
  {
    country: "Palestinian Territory, Occupied",
    alpha2: "PS",
    latitude: 32,
    longitude: 35.25,
    continent: "Asia",
  },
  {
    country: "Panama",
    alpha2: "PA",
    latitude: 9,
    longitude: -80,
    continent: "North America",
  },
  {
    country: "Papua New Guinea",
    alpha2: "PG",
    latitude: -6,
    longitude: 147,
    continent: "Oceania",
  },
  {
    country: "Paraguay",
    alpha2: "PY",
    latitude: -23,
    longitude: -58,
    continent: "South America",
  },
  {
    country: "Peru",
    alpha2: "PE",
    latitude: -10,
    longitude: -76,
    continent: "South America",
  },
  {
    country: "Philippines",
    alpha2: "PH",
    latitude: 13,
    longitude: 122,
    continent: "Asia",
  },
  {
    country: "Pitcairn",
    alpha2: "PN",
    latitude: -24.7,
    longitude: -127.4,
    continent: "Oceania",
  },
  {
    country: "Poland",
    alpha2: "PL",
    latitude: 52,
    longitude: 20,
    continent: "Europe",
  },
  {
    country: "Portugal",
    alpha2: "PT",
    latitude: 39.5,
    longitude: -8,
    continent: "Europe",
  },
  {
    country: "Puerto Rico",
    alpha2: "PR",
    latitude: 18.25,
    longitude: -66.5,
    continent: "North America",
  },
  {
    country: "Qatar",
    alpha2: "QA",
    latitude: 25.5,
    longitude: 51.25,
    continent: "Asia",
  },
  {
    country: "Réunion",
    alpha2: "RE",
    latitude: -21.1,
    longitude: 55.6,
    continent: "Africa",
  },
  {
    country: "Romania",
    alpha2: "RO",
    latitude: 46,
    longitude: 25,
    continent: "Europe",
  },
  {
    country: "Russian Federation",
    alpha2: "RU",
    latitude: 60,
    longitude: 100,
    continent: "Europe",
  },
  {
    country: "Rwanda",
    alpha2: "RW",
    latitude: -2,
    longitude: 30,
    continent: "Africa",
  },
  {
    country: "Saint Helena, Ascension and Tristan da Cunha",
    alpha2: "SH",
    latitude: -15.9333,
    longitude: -5.7,
    continent: "Africa",
  },
  {
    country: "Saint Kitts and Nevis",
    alpha2: "KN",
    latitude: 17.3333,
    longitude: -62.75,
    continent: "North America",
  },
  {
    country: "Saint Lucia",
    alpha2: "LC",
    latitude: 13.8833,
    longitude: -61.1333,
    continent: "North America",
  },
  {
    country: "Saint Pierre and Miquelon",
    alpha2: "PM",
    latitude: 46.8333,
    longitude: -56.3333,
    continent: "North America",
  },
  {
    country: "Saint Vincent and the Grenadines",
    alpha2: "VC",
    latitude: 13.25,
    longitude: -61.2,
    continent: "North America",
  },
  {
    country: "Samoa",
    alpha2: "WS",
    latitude: -13.5833,
    longitude: -172.3333,
    continent: "Oceania",
  },
  {
    country: "San Marino",
    alpha2: "SM",
    latitude: 43.7667,
    longitude: 12.4167,
    continent: "Europe",
  },
  {
    country: "Sao Tome and Principe",
    alpha2: "ST",
    latitude: 1,
    longitude: 7,
    continent: "Africa",
  },
  {
    country: "Saudi Arabia",
    alpha2: "SA",
    latitude: 25,
    longitude: 45,
    continent: "Asia",
  },
  {
    country: "Senegal",
    alpha2: "SN",
    latitude: 14,
    longitude: -14,
    continent: "Africa",
  },
  {
    country: "Serbia",
    alpha2: "RS",
    latitude: 44,
    longitude: 21,
    continent: "Europe",
  },
  {
    country: "Seychelles",
    alpha2: "SC",
    latitude: -4.5833,
    longitude: 55.6667,
    continent: "Africa",
  },
  {
    country: "Sierra Leone",
    alpha2: "SL",
    latitude: 8.5,
    longitude: -11.5,
    continent: "Africa",
  },
  {
    country: "Singapore",
    alpha2: "SG",
    latitude: 1.3667,
    longitude: 103.8,
    continent: "Asia",
  },
  {
    country: "Slovakia",
    alpha2: "SK",
    latitude: 48.6667,
    longitude: 19.5,
    continent: "Europe",
  },
  {
    country: "Slovenia",
    alpha2: "SI",
    latitude: 46,
    longitude: 15,
    continent: "Europe",
  },
  {
    country: "Solomon Islands",
    alpha2: "SB",
    latitude: -8,
    longitude: 159,
    continent: "Oceania",
  },
  {
    country: "Somalia",
    alpha2: "SO",
    latitude: 10,
    longitude: 49,
    continent: "Africa",
  },
  {
    country: "South Africa",
    alpha2: "ZA",
    latitude: -29,
    longitude: 24,
    continent: "Africa",
  },
  {
    country: "South Georgia and the South Sandwich Islands",
    alpha2: "GS",
    latitude: -54.5,
    longitude: -37,
    continent: "Antarctica",
  },
  {
    country: "Spain",
    alpha2: "ES",
    latitude: 40,
    longitude: -4,
    continent: "Europe",
  },
  {
    country: "Sri Lanka",
    alpha2: "LK",
    latitude: 7,
    longitude: 81,
    continent: "Asia",
  },
  {
    country: "Sudan",
    alpha2: "SD",
    latitude: 15,
    longitude: 30,
    continent: "Africa",
  },
  {
    country: "Suriname",
    alpha2: "SR",
    latitude: 4,
    longitude: -56,
    continent: "South America",
  },
  {
    country: "Svalbard and Jan Mayen",
    alpha2: "SJ",
    latitude: 78,
    longitude: 20,
    continent: "Europe",
  },
  {
    country: "Swaziland",
    alpha2: "SZ",
    latitude: -26.5,
    longitude: 31.5,
    continent: "Africa",
  },
  {
    country: "Sweden",
    alpha2: "SE",
    latitude: 62,
    longitude: 15,
    continent: "Europe",
  },
  {
    country: "Switzerland",
    alpha2: "CH",
    latitude: 47,
    longitude: 8,
    continent: "Europe",
  },
  {
    country: "Syrian Arab Republic",
    alpha2: "SY",
    latitude: 35,
    longitude: 38,
    continent: "Asia",
  },
  {
    country: "Taiwan, Province of China",
    alpha2: "TW",
    latitude: 23.5,
    longitude: 121,
    continent: "Asia",
  },
  {
    country: "Tajikistan",
    alpha2: "TJ",
    latitude: 39,
    longitude: 71,
    continent: "Asia",
  },
  {
    country: "Tanzania, United Republic of",
    alpha2: "TZ",
    latitude: -6,
    longitude: 35,
    continent: "Africa",
  },
  {
    country: "Thailand",
    alpha2: "TH",
    latitude: 15,
    longitude: 100,
    continent: "Asia",
  },
  {
    country: "Timor-Leste",
    alpha2: "TL",
    latitude: -8.55,
    longitude: 125.5167,
    continent: "Asia",
  },
  {
    country: "Togo",
    alpha2: "TG",
    latitude: 8,
    longitude: 1.1667,
    continent: "Africa",
  },
  {
    country: "Tokelau",
    alpha2: "TK",
    latitude: -9,
    longitude: -172,
    continent: "Oceania",
  },
  {
    country: "Tonga",
    alpha2: "TO",
    latitude: -20,
    longitude: -175,
    continent: "Oceania",
  },
  {
    country: "Trinidad and Tobago",
    alpha2: "TT",
    latitude: 11,
    longitude: -61,
    continent: "North America",
  },
  {
    country: "Tunisia",
    alpha2: "TN",
    latitude: 34,
    longitude: 9,
    continent: "Africa",
  },
  {
    country: "Turkey",
    alpha2: "TR",
    latitude: 39,
    longitude: 35,
    continent: "Asia",
  },
  {
    country: "Turkmenistan",
    alpha2: "TM",
    latitude: 40,
    longitude: 60,
    continent: "Asia",
  },
  {
    country: "Turks and Caicos Islands",
    alpha2: "TC",
    latitude: 21.75,
    longitude: -71.5833,
    continent: "North America",
  },
  {
    country: "Tuvalu",
    alpha2: "TV",
    latitude: -8,
    longitude: 178,
    continent: "Oceania",
  },
  {
    country: "Uganda",
    alpha2: "UG",
    latitude: 1,
    longitude: 32,
    continent: "Africa",
  },
  {
    country: "Ukraine",
    alpha2: "UA",
    latitude: 49,
    longitude: 32,
    continent: "Europe",
  },
  {
    country: "United Arab Emirates",
    alpha2: "AE",
    latitude: 24,
    longitude: 54,
    continent: "Asia",
  },
  {
    country: "United Kingdom",
    alpha2: "GB",
    latitude: 54,
    longitude: -2,
    continent: "Europe",
  },
  {
    country: "United States of America",
    alpha2: "US",
    latitude: 38,
    longitude: -97,
    continent: "North America",
  },
  {
    country: "United States Minor Outlying Islands",
    alpha2: "UM",
    latitude: 19.2833,
    longitude: 166.6,
    continent: "Oceania",
  },
  {
    country: "Uruguay",
    alpha2: "UY",
    latitude: -33,
    longitude: -56,
    continent: "South America",
  },
  {
    country: "Uzbekistan",
    alpha2: "UZ",
    latitude: 41,
    longitude: 64,
    continent: "Asia",
  },
  {
    country: "Vanuatu",
    alpha2: "VU",
    latitude: -16,
    longitude: 167,
    continent: "Oceania",
  },
  {
    country: "Venezuela, Bolivarian Republic of",
    alpha2: "VE",
    latitude: 8,
    longitude: -66,
    continent: "South America",
  },
  {
    country: "Viet Nam",
    alpha2: "VN",
    latitude: 16,
    longitude: 106,
    continent: "Asia",
  },
  {
    country: "Virgin Islands, British",
    alpha2: "VG",
    latitude: 18.5,
    longitude: -64.5,
    continent: "North America",
  },
  {
    country: "Virgin Islands, U.S.",
    alpha2: "VI",
    latitude: 18.3333,
    longitude: -64.8333,
    continent: "North America",
  },
  {
    country: "Wallis and Futuna",
    alpha2: "WF",
    latitude: -13.3,
    longitude: -176.2,
    continent: "Oceania",
  },
  {
    country: "Western Sahara",
    alpha2: "EH",
    latitude: 24.5,
    longitude: -13,
    continent: "Africa",
  },
  {
    country: "Yemen",
    alpha2: "YE",
    latitude: 15,
    longitude: 48,
    continent: "Asia",
  },
  {
    country: "Zambia",
    alpha2: "ZM",
    latitude: -15,
    longitude: 30,
    continent: "Africa",
  },
  {
    country: "Zimbabwe",
    alpha2: "ZW",
    latitude: -20,
    longitude: 30,
    continent: "Africa",
  },
  {
    country: "Afghanistan",
    alpha2: "AF",
    latitude: 33,
    longitude: 65,
    continent: "Asia",
  },
];
